### ISSUE TITLE
Is it impossible to import anything else than the ts files from ts files?

### ISSUE THREAD

**Issue by lukasz-zaroda** [sensiolabs/AssetMapperTypeScriptBundle#43]
Coming from the Webpack world, it seems to me that the current method of storing and serving compiled files from the `var/typescript` directory makes it impossible in `ts` files to import anything else than the `ts` files. Am I correct?

I guess I got used too much to the Webpack's loaders concept. But there is also another concern. If I want to use `ts` exclusively, I pretty much cannot make a use of the `importmaps` correct? Because they require a `js` entrypoint, and this entrypoint cannot be produced by this bundle because the output is stored in the `var/typescript/assets` directory. I actually tried to add this path to the AssetMapper's configuration, thinking that maybe then it will be able to pick up the produced `js` files, but it doesn't seem to be the case.

So, given that this bundle is advertized in the AssetMapper's documentation, it seems weirdly incompatible at first glance. Even its documentation doesn't give an example of using AssetMapper features, but it uses the ol' `asset()` function, instead.

What am I missing?

I would just like to be able to produce the entrypoint `app.js` used by the AssetMapper from the typescript. Is that possible?

**Edit:**
I think I got it. The app.js that is not produced from the typescript HAS TO be the entrypoint. It can, however, import `ts` files. And then `ts` files can import other files, like `css` files. I think that's an important thing that's missing from the docs. Trying to produce the initial `app.js` from the typescript will be a common pitfall, I think.

**Edit #2:**
Actually I just figured that you need to edit the `importmap.php` file in the root of the project to change entrypoint and then it CAN be changed into a `ts` file. What confused me is that this is a configuration that is not inside the `config/` directory. So everything seems to work great! Sorry for not reading the AssetMapper docs more carefully ^^" . This issue can be closed.

**Comment by maelanleborgne** [comment]
Hello @lukasz-zaroda , I'm sorry that you encountered issues setting up the bundle.  
I am well aware that the documentation is lacking some clear guidelines to get started, I'm working on it.  
So basically yes, typescript entrypoints are available if you set them up in importmap.js, otherwise importing typescript files from js files is another way to to use the bundle. Or at last you can simply use the good old `<script src="{{ asset('my_asset.js') }}" type="module"/>`.   
Anyway, it seems you've managed to make it work correctly so enjoy :) .
