### ISSUE TITLE
TypeScript Build Watch Mode does not work with compiled assets in `public/`

### ISSUE THREAD

**Issue by nitwhiz** [sensiolabs/AssetMapperTypeScriptBundle#58]
The command `bin/console typescript:build --watch` will watch for changes and (seemingly) compile them, but as long as there is a built source in `public/assets`, the changes won't reflect in browser.

Deleting `public/assets` worked for me, `--watch` now picks up on changes and they're reflected in browser.

I have caching disabled in my browser.

**Comment by maelanleborgne** [comment]
Hello @nitwhiz. This is the normal behavior of asset mapper (https://symfony.com/doc/current/frontend/asset_mapper.html#serving-assets-in-dev-vs-prod). In dev, if you wish to see your changes reflected automatically in the browser, you should not run `asset-map:compile` and make sure you don't have a `public/assets`. It seems like you figured out already how to work around this, and since it's not an issue with this bundle I'll close the issue.  
Feel free to reopen if you think there really is an issue.
